### ISSUE TITLE
Make examples run on Windows

### ISSUE THREAD

**Issue by developer239** [yahoo/react-intl#821]
Could you pleeeeease fix your example start script so that they run on windows? I am surprised that library with  3 885 stars does not do this already.

**Comment by ericf** [comment]
Feel free to send a PR to fix it. I don't have a Windows machine.

**Comment by OracPrime** [comment]
I've forked a copy onto my windows dev environment.  The install itself (npm install) works without error.  The lint test fails with 5823 errors because (as with most github projects) lint is set to expect Unix line endings, but Git converts the line endings when you fetch to Windows - so I've downgraded this to a warning so that whilst it's annoying for Windows users still, it doesn't actually stop them doing things.  There's then a problem with the command to build the examples.  This is the first instance of the problem on Windows (I can't believe there isn't a generic solution yet) that Windows needs babel-node.cmd rather than babel-node.  I've put a fix in for this in the examples.js file; I haven't yet worked out how to put a fix in for the package.json files.  However since this is enough to make at least some of the examples build under windows, I'm creating a PR.  While I was at it, I changed the hello world sample to actually use a non-us locale to a) show how to do it and b) produce an output that was different to the input.  I'll keep looking for a solution to the generic babel-node on windows problem.

So summary for Windows:
install: works
tests: lint fails, downgraded to warn by my PR.  With PR all tests work
samples:   examples:install now works with my PR
hello world - works post PR with noticeably translated output
aync, nested, translations - fail still with node-babel issue
react-router - fails.  Seems to be some problem with the alpha release of react-router v4

**Comment by developer239** [comment]
Thank you for the time that you spent on this issue. I really appreciate it.

**Comment by ericf** [comment]
I merged @OracPrime's PR https://github.com/yahoo/react-intl/pull/839

**Comment by OracPrime** [comment]
I'm not convinced it's closed - the nested examples still won't build properly on windows.  When I can get a response from the cross-env and/or cross-spawn teams we can probably reopen, apply an updated version dependency on the right version, insert cross-env into the right package.json and we're done.

**Comment by ericf** [comment]
Okay, no worries, I'll reopen it…

**Comment by OracPrime** [comment]
D'oh! I've found the (very easy) fix.  Do I need to open a new pull request?  I pushed to the old one, but it doesn't seem to have registered...

**Comment by ericf** [comment]
Yeah, `fetch upstream` and create a new branch from `upstream/master` with the change, and open a new PR,

**Comment by OracPrime** [comment]
PR opened.  I believe this now closes this issue.

**Comment by ericf** [comment]
Okay, thanks again, merged.

**Comment by RonPenton** [comment]
I still get an error building the examples on Windows. 

```
C:\CODE\cpss\react-intl\examples\translations>npm run build

> react-intl-example-translations@1.0.0 build C:\CODE\cpss\react-intl\examples\translations
> npm run build:bundle && npm run build:langs


> react-intl-example-translations@1.0.0 build:bundle C:\CODE\cpss\react-intl\examples\translations
> ../../node_modules/.bin/cross-env ../../node_modules/.bin/mkdirp build && ../../node_modules/.bin/cross-env ../../node_modules/.bin/brows
erify src/client/index.js -d -t babelify -t browserify-shim > build/bundle.js

'..' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-intl-example-translations@1.0.0 build:bundle: `../../node_modules/.bin/cross-env ../../node_modules/.bin/mkdirp build && ../
../node_modules/.bin/cross-env ../../node_modules/.bin/browserify src/client/index.js -d -t babelify -t browserify-shim > build/bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-intl-example-translations@1.0.0 build:bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rlp2\AppData\Roaming\npm-cache\_logs\2017-09-19T16_27_35_826Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-intl-example-translations@1.0.0 build: `npm run build:bundle && npm run build:langs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-intl-example-translations@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by developer239** [comment]
@RonPenton Just install linux or buy macbook air. Working with node / react on windows is terrible experience.

**Comment by RonPenton** [comment]
@developer239 How about no. Have anything useful to contribute?

**Comment by developer239** [comment]
@RonPenton I am the guy who started the issue and even I don't use window anymore. Suit yourself. :)
